#!/bin/bash 
export APIHOST=""
export APIPORT=""
export VITEHOST=""
export VITEPORT="443"

if [[ $EUID > 0 ]]; then # we can compare directly with this syntax.
  	echo "Please run as root/sudo"
  	exit 1
else
	nodemon api
fi
